### ISSUE TITLE
Feature to drain Kafka Queue

### ISSUE THREAD

**Issue by docktermj** [Senzing/stream-loader#10]
**Is your feature request related to a problem? Please describe.**
The problem is to figure out how fast Kafka can spit out messages.

**Describe the solution you'd like**
Create a subcommand that consumes from the Kafka queue and does nothing but read and commit.

**Comment by docktermj** [comment]
Pull Request:

- https://github.com/Senzing/stream-loader/pull/11

**Comment by jeffadair** [comment]
stream-logger will drain a queue. It supports rabbitmq, sqs, and kafka at the moment and we add more as we need to.

It will log the records as they come out of the queue. If that is a problem, then create an issue on the stream-logger for a quiet mode, or something like that. 

https://github.com/Senzing/stream-logger
