### ISSUE TITLE
create a way to use different libmysqlclient.so.21 files for RHEL vs Debian for MySQL users

### ISSUE THREAD

**Issue by NilayBhatt** [Senzing/stream-loader#107]

**Comment by docktermj** [comment]
When using docker containers, the senzing/init-container takes care of this https://github.com/Senzing/docker-init-container/blob/849aa22d17d64207ababbd603cf6074548916852/init-container.py#L1204-L1242

For use of `stream-loader.py` in a non-dockerized enviroment, some documentation is needed.

**Comment by docktermj** [comment]
Slightly related: https://github.com/Senzing/docker-init-container/issues/75

**Comment by docktermj** [comment]
Work being done at https://github.com/Senzing/knowledge-base/blob/master/HOWTO/install-libmysqlclient21.md

**Comment by docktermj** [comment]
Other articles

1. https://senzing.zendesk.com/hc/en-us/articles/360026660814-Setup-MySQL-on-Debian-Linux
2. https://senzing.zendesk.com/hc/en-us/articles/360026782513-Setup-MySQL-on-Red-Hat-CentOS-Linux

**Comment by docktermj** [comment]
For Centos, I'll be looking at https://pkgs.org/download/libmysqlclient.so.21()(64bit)

**Comment by docktermj** [comment]
@NilayBhatt I've documented how to install `libmysqlclient.so.21` manually on CentOS (i.e. RedHat) and Ubuntu at https://github.com/Senzing/knowledge-base/blob/master/HOWTO/install-libmysqlclient21.md

Is that sufficient to close this issue?

**Comment by docktermj** [comment]
Hi @NilayBhatt Just to keep things tidy,  I'll close this issue in 7 days unless you specify to keep it open.

**Comment by docktermj** [comment]
Closing.
