### ISSUE TITLE
The stream-loader shouldn't shut down a thread when the queue is empty.

### ISSUE THREAD

**Issue by docktermj** [Senzing/stream-loader#117]
**Is your feature request related to a problem? Please describe.**
The use of `exit_error()` causes threads to die and cripple a running stream-loader.

**Describe the solution you'd like**
On a case-by-case basis,  figure out a different strategy for how to handle errors in threads and remove `exit_error()` calls.

**Comment by docktermj** [comment]
With new found discoveries of use in AWS AutoScale,  the stream-loader needs to figure out how to respond to queue empty situations and release database connections.

**Comment by davdasil** [comment]
I think you need to add ```self.exit_on_empty_queue = self.config.get('exit_on_empty_queue')``` to line 1955 so this class is consistent with ReadSqsWriteG2Thread(WriteG2Thread) and does not fail when the SQS queue is empty.

**Comment by docktermj** [comment]
@davdasil Right you are!  Thank you.

As the code is, it would fail on this line:  https://github.com/Senzing/stream-loader/blob/b5e18f1d484131e3a9d6e8091f716d8b381f1ac8/stream-loader.py#L2028

Notes:

1. https://github.com/Senzing/stream-loader/blob/b5e18f1d484131e3a9d6e8091f716d8b381f1ac8/stream-loader.py#L1837

**Comment by docktermj** [comment]
@davdasil The fix you recognized is now in the master branch.  Again, thanks!

**Comment by docktermj** [comment]
Pull requests

1. https://github.com/Senzing/stream-loader/pull/129
2. https://github.com/Senzing/stream-loader/pull/130
3. https://github.com/Senzing/stream-loader/pull/134
4. https://github.com/Senzing/stream-loader/pull/135
5. https://github.com/Senzing/stream-loader/pull/136
6. https://github.com/Senzing/stream-loader/pull/138
7. https://github.com/Senzing/stream-loader/pull/141
