### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by eruser1** [Senzing/stream-loader#121]
The boto3 library needs to be added to requirements.txt

**Comment by docktermj** [comment]
Pull Requests

https://github.com/Senzing/stream-loader/pull/122

**Comment by docktermj** [comment]
@eruser1 If this satisfies your issue, please close the issue.

Thank you for identifying this problem.

**Comment by docktermj** [comment]
@eruser1 Just checking in to make sure this fixed your issue.   Let us know if there's anything more that needs to be done.  If we don't hear back in a week, we'll close the issue.

**Comment by docktermj** [comment]
Closing.  Haven't heard from customer.
