### ISSUE TITLE
ReadSqsWriteG2WithInfoThread tries to write warning with a kafka topic in the log

### ISSUE THREAD

**Issue by kieranswhite** [Senzing/stream-loader#131]
I have been using the stream-loader container (**1.5.4**) with SQS and the info queue functionality. When running the loader it failed to add a message to the failure queue and the warning message also errored.

Looking at lines [1938 ](https://github.com/Senzing/stream-loader/blob/7392c807df4f53905966f390c7abb12bd23e9866/stream-loader.py#L1938) and [1952](https://github.com/Senzing/stream-loader/blob/7392c807df4f53905966f390c7abb12bd23e9866/stream-loader.py#L1952) it appears that the logger tries to write down the value of the info/failure topics respectively which won't exist for an SQS implementation. 

I believe this should be changed to `info_queue_url` and `failure_queue_url` to ensure errors are appropriately logged.  

Thanks,

Kieran

**Comment by docktermj** [comment]
Hi @kieranswhite!

Thanks for pointing this out.   ...and how timely!

One of the thing's I'm working on in a different branch is to use the AWS SQS Dead Letter Queue (DLQ) Current link: https://github.com/Senzing/docker-compose-aws-ecscli-demo/tree/issue-24.dockter.1/docs/advanced#provision-simple-queue-service

I'll certainly correct this issue and will also figure out the interaction with SQS DLQ.

Just curious, for your implementation would you probably use a `failure_queue_url` type of queue or a DLQ.   ...or does it matter?

**Comment by docktermj** [comment]
@kieranswhite I've updated the master branch with fix.   If it is sufficient, please close the issue.   If not sufficient, let me know where it is deficient.

If you are using docker, `senzing-environment:latest` will be updated (https://hub.docker.com/r/senzing/senzing-environment/tags). If you pin to releases, which is a good idea, I'll be making a new release once https://github.com/Senzing/stream-loader/issues/117 is complete.   Probably in 2-3 days.

**Comment by kieranswhite** [comment]
Hi @docktermj, Thanks for the speedy response! That's great thanks for making the change. With regards to the Failure queue / DL queue I'm going to discuss with my colleagues so I'll have to get back to you on that one.

Thanks,

Kieran
