### ISSUE TITLE
Error seen in GitAction

### ISSUE THREAD

**Issue by docktermj** [Senzing/stream-loader#133]
**Describe the bug**
Seeing errors in the GitActions.

```console
##[error]fatal: couldn't find remote ref refs/pull/132/merge
```

1. https://github.com/Senzing/stream-loader/actions
2. https://github.com/Senzing/stream-loader/runs/976119502

**Comment by mahchiahui** [comment]
Git branch was merged and deleted too quickly, before the git action could finished running. As such, this resulted in a failure within git actions when it could not find the deleted branch. The solution to this would be to only merge after the git actions builds have finished running
