### ISSUE TITLE
Increase RabbitMQ heartbeat timeout

### ISSUE THREAD

**Issue by docktermj** [Senzing/stream-loader#146]
**Is your feature request related to a problem? Please describe.**
Currently when using `stream-loader.py` and a Governor that may pause for minutes, the RabbitMQ connection is terminated.

**Describe the solution you'd like**
Increase the RabbitMQ timeout for heartbeats.  
See https://pika.readthedocs.io/en/stable/examples/heartbeat_and_blocked_timeouts.html

Note:  One of the Governors to consider is https://github.com/Senzing/governor-postgresql-transaction-id   So the heartbeat timeout would have to be larger than the time it takes to "vacuum" PostgreSQL.

**Comment by docktermj** [comment]
Since applications may require different timeouts, maybe we should support an environment variable like:
`SENZING_RABBITMQ_HEARTBEAT_TIMEOUT`.

**Comment by jeffadair** [comment]
Was covered by #160 #166
