### ISSUE TITLE
Importing governor to use postgresql governor on first use

### ISSUE THREAD

**Issue by jeffadair** [Senzing/stream-loader#173]
On the code section quoted below we import 'senzing_governor'. This works fine in most cases. However, docker-init-container will automatically download the senzing postgresql governor when appropriate. That will happen too late to get picked up by this import statement on the first run of a docker-compose formation. Once the governor is there (ie the first run of the docker-init-container for a given install.) it will function correctly

https://github.com/Senzing/stream-loader/blob/5191c6841cc6496a3e2e334947f033083994c210/stream-loader.py#L3483-L3488

This section of code might be better located in the common_prolog after the startup delay: https://github.com/Senzing/stream-loader/blob/5191c6841cc6496a3e2e334947f033083994c210/stream-loader.py#L2932

**Comment by docktermj** [comment]
Yes, this is an issue.  Good find!

I'm hoping to not pollute runtime services with tasks that should be in initialization-time jobs.  This may also create issues with permissions where initialization may run with elevated permissions, but services do not.

Perhaps we can create some sort of signal once the init-container has completed such that the stream-loader (and other services relying on init-container) can pause or exit if init-container has not completed.

**Comment by docktermj** [comment]
Perhaps `senzing/init-container` could create a file at `/var/opt/senzing/sentinels/init-container.sentinel` to let other processes know that the initialization process is complete.   (Not sure if "sentinel" is the best word)

**Comment by jeffadair** [comment]
Covered by #177
