### ISSUE TITLE
SQS Connection fails when using SQS VPC Endpoints

### ISSUE THREAD

**Issue by dev-eng1** [Senzing/stream-loader#195]
**Describe the bug**
When using SQS VPC endpoints there is a feature that means that the SQS client has to be initialised with the correct endpoint as described at https://github.com/boto/boto3/issues/1900, https://github.com/boto/boto3/issues/2172 and others as otherwise it attempts to connect to endpoint URL 'https:\<region\>.queue.amazonaws.com' which fails rather than the VPC endpoint at https://sqs.\<region\>.amazonaws.com

**To Reproduce**

Create an AWS VPC
Create a private subnet in VPC
Create a SQS endpoint in VPC
Create a SQS queue
Run stream-loader in an EC2 within private subnet and watch it fail connecting to SQS queue

**Additional context**
The solution is that the correct endpoint domain is already in the SQS queue URL and works whether VPC endpoints are being used or not. So:
  self.sqs = boto3.client("sqs")
becomes
  import re
  ...
  PATTERN = "^([^/^:]+)/"
  ...
  pat = re.compile(PATTERN)
  m = pat.match(URL)
  if m is None:
    ERROR
  self.client = boto3.client(
    'sqs',
    endpoint = m.group(1)
  )

**Comment by docktermj** [comment]
@dev-eng1 You pull request has been merged in and I've also massaged your code a little.    If you are satisfied with the change, go ahead and close this issue.    If there's something we've missed, please let us know.

**Comment by docktermj** [comment]
@dev-eng1  Let me know if your issue has been addressed.  If we don't hear back in 7 days, we'll go ahead and close the issue.
