### ISSUE TITLE
SQS Info queue delay time not configurable

### ISSUE THREAD

**Issue by dev-eng1** [Senzing/stream-loader#202]
**Is your feature request related to a problem? Please describe.**
When messages are posted to the info queue, stream-loader hard codes the delay time to 10s. This overrides any delay specified on the SQS queue. To reduce churn in downstream systems when multiple records are received that affect the same entity in quick succession we wish to increase this delay.

**Describe the solution you'd like**
The delay should be configurable, with a default of 10s

**Comment by docktermj** [comment]
Pull Requests:

1. https://github.com/Senzing/stream-loader/pull/203
2. https://github.com/Senzing/stream-loader/pull/204

**Comment by docktermj** [comment]
@dev-eng1 A new `senzing/stream-loader:1.7.2` docker image is available on DockerHub (https://hub.docker.com/r/senzing/stream-loader/tags?page=1&ordering=last_updated)

Let us know if there is more to do.  If not, please close this issue.
