### ISSUE TITLE
Error not captured when testing a G2Loader.py load

### ISSUE THREAD

**Issue by Lohrax** [Senzing/stream-loader#249]
We provide a sample NPI dataset that can be loaded via a demonstration here: https://senzing.com/connections-in-ppp-loan-data/ 

This data is already formatted and should be easily ingested.  If you run this through G2Loader Test (e.g. ./G2Loader.py -f NPI_Orgs_LasVegas.csv/?data_source=NPI_ORGANIZATION,file_format=CSV -T) it will fail on every row because there is a column of ENTITY_TYPE with a value of ORGANIZATION.  By default we do not have an Organization entity type, easy enough to create but I think the error should be captured and summarized.

**Comment by docktermj** [comment]
@Lohrax If I understand the issue correctly, this is an issue with `G2Loader.py`  (not `stream-loader.py`).   If my understanding is correct, please open a similar issue in https://github.com/Senzing/g2loader and close this issue.   

If this is an issue with `stream-loader.py`,  please try to re-explain.  I'm not getting the connection.
