### ISSUE TITLE
Unqualified exception name in stream-loader.py

### ISSUE THREAD

**Issue by jeffadair** [Senzing/stream-loader#25]
Line 1569 has the exception name as G2ModuleException. Should be G2Exception.G2ModuleException.

**Comment by jeffadair** [comment]
Fixed by https://github.com/Senzing/stream-loader/commit/b671e31715ce5dc7a9ebffbe3a8581a73a5f02e1

**Comment by docktermj** [comment]
Pull Request

1. https://github.com/Senzing/stream-loader/pull/26
