### ISSUE TITLE
Stream loader can't re-establish connections to RabbitMQ  info and failure queues.

### ISSUE THREAD

**Issue by awintersi** [Senzing/stream-loader#253]
**Describe the bug**
If the rabbitmq_queue is left empty connection to rabbitmq_info_queue and  rabbitmq_failure_queue are lost and can't be re-established.

**To Reproduce**
Follow the steps [here ](https://github.com/Senzing/kubernetes-demo/blob/master/docs/helm-rabbitmq-postgresql/README.md) to bring up a Senzing stack on Kubernetes using Helm, RabbitMQ, and a PostgreSQL database, with the exception of using rabbitmq-withinfo:

`helm install  ${DEMO_PREFIX}-senzing-stream-loader senzing/senzing-stream-loader  --namespace ${DEMO_NAMESPACE}  --values ${HELM_VALUES_DIR}/stream-loader-rabbitmq-postgresql.yaml --version 1.3.0 --set senzing.subcommand=rabbitmq-withinfo`

After all rabbitmq_queue messages have been consumed by stream loader the following output appears in the stream loader log, and further messages added to the rabbitmq_queue are not consumed.

`2021-12-09 13:33:46,205 senzing-50010880E Unspecific error when info_channel.basic_publish().. Error: 'tuple' object has no attribute 'basic_publish'
2021-12-09 13:33:46,205 senzing-50010698E Program terminated with error.`

In stream-loader.py, these are the initial calls (on startup) to assign the info and failure channels:

https://github.com/Senzing/stream-loader/blob/828979af4ea45a76208c152e7a46705d45554992/stream-loader.py#L2469
https://github.com/Senzing/stream-loader/blob/828979af4ea45a76208c152e7a46705d45554992/stream-loader.py#L2474

but to reconnect they are missing the index ([1])
https://github.com/Senzing/stream-loader/blob/828979af4ea45a76208c152e7a46705d45554992/stream-loader.py#L2360
https://github.com/Senzing/stream-loader/blob/828979af4ea45a76208c152e7a46705d45554992/stream-loader.py#L2324

**Expected behavior**
Stream loader will be able to re-establish a connection to the info and failure queues.

**Comment by jeffadair** [comment]
@awintersi , I just created a new release (1.9.3) that has the fix you requested. Thanks for bringing it to our attention.

Please try the new release and, if it works for you, please close this issue. Thanks!

**Comment by awintersi** [comment]
Thanks @jeffadair , 1.9.3 works for me.
