### ISSUE TITLE
TLS support for Kafka

### ISSUE THREAD

**Issue by Lohrax** [Senzing/stream-loader#260]
Would like to have TLS configuration for our stream-loader to support Kafka.  At this time stream-loader is more important then stream-producer.

**Comment by docktermj** [comment]
Some tips:

- https://github.com/confluentinc/confluent-kafka-go/issues/568

**Comment by docktermj** [comment]
Pull requests:

1. https://github.com/Senzing/stream-loader/pull/263
2. https://github.com/Senzing/stream-loader/pull/268
