### ISSUE TITLE
MONITOR check should be 1min instead of 10min

### ISSUE THREAD

**Issue by brianmacy** [Senzing/stream-loader#271]
10 minutes is just way too long for the stream-loader (and redoer) to realize they are not functioning.

For instance, if the MQ doesn't exist all threads die as soon as they try to connect.  But the node stays up and "healthy" for 10+ minutes until the monitor checks.

**Comment by docktermj** [comment]
We're trying to not flood the logs with monitoring messages.  10 minutes is a default.  It can be customized by setting the ``SENZING_MONITORING_PERIOD_IN_SECONDS` environment to 60 for a per minute monitoring check.

References:
- https://github.com/Senzing/stream-loader/blob/1dbf09516c993dc51955d9dff7a0053c24dde990/stream-loader.py#L246-L250

**Comment by docktermj** [comment]
@brianmacy Logging monitoring records every 1 minute floods the logs in a long-running process.   From what I understand, you want to know at startup if something is wrong.

To address this specific issue, we can have "startup" logic that logs frequently for the first N minutes of startup and then when it is running, settle in on the logging frequency based on `SENZING_MONITORING_PERIOD_IN_SECONDS`

**Details:**    At startup, the first monitoring record is posted after 1 minute,  the second monitoring record is posted 2 minutes after that, the third monitoring record 3 minutest after that.   It add 1 minute to each cycle until `SENZING_MONITORING_PERIOD_IN_SECONDS` is reached.

Would that satisfy your requirement?

**Comment by brianmacy** [comment]
Why not always check health every 30 seconds (or 10?) and only log every 10min?  Not sure why the two things need to be tied.

**Comment by docktermj** [comment]
Ok, that's a reasonable approach.

**Comment by docktermj** [comment]
Pull requests:

- https://github.com/Senzing/stream-loader/pull/310
