### ISSUE TITLE
JSON message being written to log file when Dead Letter Queue is in use

### ISSUE THREAD

**Issue by Lohrax** [Senzing/stream-loader#274]
When a Dead Letter Queue is not in use and an error occurs with a message, that JSON message should be captured in the log file so as to have full traceability to all messages. (This works correctly)  When a Dead Letter Queue is in use and an error occurs with the message, that message should be written to the Dead Letter Queue and the log file should not have a copy of the JSON record in it (This does not work correctly).

Currently, when a Dead Letter Queue is in use and an error occurs, that JSON message is written to both the log file and the Dead Letter Queue.  Please correct. 

Reference:   https://github.com/Senzing/stream-loader/blob/d3e70ebd1eddac8f495a16708fd6d3b099f23d56/stream-loader.py#L2720-L2722

**Comment by docktermj** [comment]
Pull requests:

- https://github.com/Senzing/stream-loader/pull/275
