### ISSUE TITLE
Record loading fails if record doesn't have a RECORD_ID

### ISSUE THREAD

**Issue by glennjdea** [Senzing/stream-loader#307]
When loading records without record IDs, the record dictionary is assigned to record_id (https://github.com/Senzing/stream-loader/blob/main/stream-loader.py#L1490 ), which subsequently fails in the call to addRecordWithInfo (https://github.com/Senzing/stream-loader/blob/main/stream-loader.py#L1590) because it expects a string.  The error in the loader logs is:

Error: argument 2: <class 'TypeError'>: wrong type

This was introduced in https://github.com/Senzing/stream-loader/commit/135b336ef39db3934f4418c23df24c5f6318e27e.

**Comment by docktermj** [comment]
@glennjdea I was able to recreate.  Working on fix now.

**Comment by docktermj** [comment]
@glennjdea By the way,  Thanks for reporting this!

**Comment by glennjdea** [comment]
> @glennjdea By the way, Thanks for reporting this!

@docktermj No problem.  Thanks for getting onto it so quickly.

**Comment by glennjdea** [comment]
@docktermj thanks for providing a fix so quickly.  I'm trying to test it out now, but I need some guidance on how to use your images.

We have our own build pipeline that produces variations of your images.  Our pipeline hasn't been run yet so I don't have our variants to test.  Our images differ from yours in that they include a Senzing install (in /opt/senzing) and a Senzing project.  I'd like to test your image directly, but I'm not sure how to do so given that it doesn't contain a Senzing install or a Senzing project.  One option is to install Senzing onto my host and then mount that into the container, but that seems to defeat the object of using images if I have to install Senzing locally anyway.  I suppose I have two questions:

1. Why don't you include a Senzing install and project in your images?
2. Is there any guidance on how to prepare the volumes to mount into the containers?

Many thanks.

**Comment by glennjdea** [comment]
Many thanks @docktermj .  The issue is fixed.
