### ISSUE TITLE
Stream loader shouldn't exit on license expiration.

### ISSUE THREAD

**Issue by roncewind** [Senzing/stream-loader#357]
Per Brian:

That stream-loader/redoer expire data handling should just be a warning and not exit.  Unless the license returns the 999 error that it expired/exceeded.

There are buffers built into the engine handling.

I would actually warn if the license expires within 14 days
in fact, if you wanted to be really cool... spit out a warning  from the health monitor when it is run and logs (like every 10min?)
just save that expiration date off for it to use

**Comment by roncewind** [comment]
looks like we're exiting with these lines:  
```
 if remaining_time.days < 0:
        exit_error(885)
```

**Comment by brianmacy** [comment]
Technically it should exit on license error (core 999 I believe) but it should do it's own detection besides warning the user as the time approaches towards the expiration.
