### ISSUE TITLE
Performance tests step on each other when using multiple stream-loaders

### ISSUE THREAD

**Issue by jeffadair** [Senzing/stream-loader#41]
When the stream loader starts, G2 does a short perf test to check system capabilities. When running multiple stream loaders, these perf tests step on each other and this error is seen.

> senzing-50010515W Could not do performance test. G2 generic exeption at /opt/senzing.docker/g2/python/G2Module.ini. Error: 1011E|Unique Constraint Violation '(1062:Duplicate entry '1557336981585' for key 'PRIMARY'23000 Duplicate entry '1557336981585' for key 'PRIMARY' 23000 )'

It the container continues without adverse effects.

**Comment by docktermj** [comment]
**Note:** The senzing-50010515W warning

https://github.com/Senzing/stream-loader/blob/6450ead2fb177156ed376b30093d9169b9f706ef/stream-loader.py#L1839-L1840

has been changed to senzing-50010728W 

https://github.com/Senzing/stream-loader/blob/f9612be8e0f88f332b93eafc12986a439111c64a/stream-loader.py#L1949-L1950

**Comment by docktermj** [comment]
@jeffadair Should we do anything more?

**Comment by docktermj** [comment]
This should be fixed in Senzing 1.12.0.
