### ISSUE TITLE
Exceptions when using stream-loader with Senzing 1.9

### ISSUE THREAD

**Issue by jeffadair** [Senzing/stream-loader#44]
**Describe the bug**
Three different exceptions when running stream-loader with Senzing 1.9. Two are fatal, one is not.

**To Reproduce**
Run stream-loader with senzing 1.9 two will show up immediately, one is in the monitoring thread if when the stream-loader lives long enough to monitor status

**Expected behavior**
No excpetions!

**Comment by docktermj** [comment]
I'm not sure, but I think https://github.com/Senzing/stream-loader/issues/60 with the https://github.com/Senzing/stream-loader/pull/61 fix solves the issue of the fatal error. 

It was a case of misusing a function as a class for the `except:` clause.

@jeffadair Let me know if code delivered 2 days ago fixes the issue.

**Comment by docktermj** [comment]
Pull Requests:

1. https://github.com/Senzing/stream-loader/pull/45
