### ISSUE TITLE
Concurrency for stream-loader.py kafka

### ISSUE THREAD

**Issue by docktermj** [Senzing/stream-loader#6]
**Is your feature request related to a problem? Please describe.**
Currently the `./stream-loader.py kafka` command does not use multiprocessing nor threading.
The current version of `G2Loader.py` does and seems to get better performance.

**Describe the solution you'd like**
With the intent of `./stream-loader.py` being used in a containerized (docker) environment.  We'd like to have the number of processes controlled by the docker orchestration (Kubernetes, Docker Swarm, etc.) and the number of threads controlled by parameters to `./stream-loader.py`.

The net is that an instance of `./stream-loader.py` will occupy one process and N threads.

**Comment by docktermj** [comment]
In https://docs.python.org/3.7/library/threading.html#thread-objects

```
CPython implementation detail: In CPython, due to the Global Interpreter Lock, only one thread can execute Python code at once (even though certain performance-oriented libraries might overcome this limitation). If you want your application to make better use of the computational resources of multi-core machines, you are advised to use multiprocessing or concurrent.futures.ProcessPoolExecutor. However, threading is still an appropriate model if you want to run multiple I/O-bound tasks simultaneously.
```

**Comment by brianmacy** [comment]
You will find that since most of the work is done in native code that the lock isn't really an impact.  Probably more importantly, Senzing has a per process memory footprint which can impact scaling out a machine, using threads mitigates that impact.

**Comment by docktermj** [comment]
Pull Requests:

- https://github.com/Senzing/stream-loader/pull/7
- https://github.com/Senzing/stream-loader/pull/8
- https://github.com/Senzing/stream-loader/pull/9
