### ISSUE TITLE
Support `SENZING_ENGINE_CONFIGURATION_JSON`

### ISSUE THREAD

**Issue by docktermj** [Senzing/stream-loader#70]
**Is your feature request related to a problem? Please describe.**
Currently a somewhat "fixed format" JSON string is constructed for use with the Senzing Engine *.initV2() method.  Example: https://github.com/Senzing/stream-loader/blob/269c9dd2c51058d8294c40c6dd47574b455754a6/stream-loader.py#L1764-L1776

**Describe the solution you'd like**
For more flexible configuration of the Senzing Engine `*.initV2()` methods, determine if `SENZING_ENGINE_CONFIGURATION_JSON` is defined in the environment and if detected return that value in `get_g2_configuration_json()` functions like https://github.com/Senzing/stream-loader/blob/269c9dd2c51058d8294c40c6dd47574b455754a6/stream-loader.py#L1779-L1780

Pseudo-code

```python
if os.getenv("SENZING_ENGINE_CONFIGURATION_JSON", False):
    return os.getenv("SENZING_ENGINE_CONFIGURATION_JSON")
else:
    json.dumps(get_g2_configuration_dictionary(config))
```

Once complete, Kubernetes/Helm enablement needs to be done. Issue: https://github.com/Senzing/charts/issues/83

**Comment by docktermj** [comment]
This should also be done in:

1. https://github.com/Senzing/configurator
2. https://github.com/Senzing/docker-init-container
3. https://github.com/Senzing/docker-python-demo
4. https://github.com/Senzing/g2-configuration-initializer
5. https://github.com/Senzing/resolver

**Comment by docktermj** [comment]
Note: in the pseudo-code above `os.getenv()` was used.  The approach to use with the configuration context is:

```python
if config.get('engine_configuration_json'):
    return config.get('engine_configuration_json')
else:
    json.dumps(get_g2_configuration_dictionary(config))
```

**Comment by docktermj** [comment]
Tips on JSON in YAML file:

- https://stackoverflow.com/questions/3790454/how-do-i-break-a-string-over-multiple-lines

**Comment by ssasidharanwp** [comment]
This would greatly help whitepages make our senzing entity resolution run faster. Thanks !!

**Comment by docktermj** [comment]
Pull requests:

1. https://github.com/Senzing/stream-loader/pull/73
